title: Kaustubh's blogs.
author: kaustubhdeokar
theme: minima
email: kaustubhdeokar@pm.me.com
description: > # this means to ignore newlines until "baseurl:"
  Try to inculcate a habit for blogging.

# social links
twitter_username: k_devkar26 # DO NOT include the @ character, or else the build will fail!
github_username:  kaustubhdeokar # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
